---
title: "Lessons and Examples"
---

```{r setup, include = FALSE, warning = FALSE}
library(tidyverse)
library(stringr)
library(htmltools)
tagList(rmarkdown::html_dependency_font_awesome())
```

```{r file-list, include = FALSE, warning = FALSE}
has_all_things <- function(y, things) {
  all(match(tolower(things), tolower(y), nomatch = 0) > 0)
}
parse_yaml <- function(file, n = 15) {
  rmarkdown:::parse_yaml_front_matter(read_lines(file, n_max = n))
}
ext_file <- function(file, ext) paste(file, ext, sep = ".")
cat_bullet <- function(x, pattern) {
  x <- x %>% 
    filter(str_detect(basename, pattern))
  cat(x$bullet)
}

x <- tibble(fls = list.files()) %>%
  mutate(basename = tools::file_path_sans_ext(fls),
         ext = tools::file_ext(fls)) %>% 
  group_by(basename) %>% 
  summarize_all(list) %>% 
  filter(map_lgl(ext, has_all_things, things = c("Rmd", "html")))

x <- x %>% 
  mutate(
    yaml = basename %>% ext_file("Rmd") %>% map(parse_yaml),
    title = yaml %>% map_chr("title"),
    comment = yaml %>% map_chr("comment", .null = ""),
    href = map2(ext_file(basename, "html"), title, ~ a(href = .x, .y)) %>%
      map_chr(as.character),
    bullet = map2_chr(href, comment, ~ paste("*", .x, .y, "\n"))
  )
```

### Background basics

```{r results = 'asis', echo = FALSE}
cat_bullet(x, "^bk")
```

### Core purrr lessons

```{r results = 'asis', echo = FALSE}
cat_bullet(x, "^ls")
```

### Worked examples

```{r results = 'asis', echo = FALSE}
cat_bullet(x, "^ex")
```

### Patterns and anti-patterns

```{r results = 'asis', echo = FALSE}
cat_bullet(x, "^pt")
```

This work is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).

